export const portfolio_data= [
    {
      id : 1,
      imgSrc: 'assets/img/portfolio/portfolio-1.png',
      name: 'MyDict',
      category : 'website',
      url : '',
      tech : 'Html,Css,Js',
      desc : 'MyDict is an simple dictionary app created with dictionary API . It gives the meaning and phoenetics of the word. It also states the example of given word. There is also option of spelling the word.',
    },
    {
      id : 2,
      imgSrc: 'assets/img/portfolio/portfolio-2.png',
      name: 'News.com',
      category : 'website',
      url : '',
      tech : 'React.js , newsapi',
      desc : ' News.com is a simple react app created with react.js. It shows various news headlines of various categories in India. News are categorized according to their type for simplicity.',
    },
    {
      id : 3,
      imgSrc: 'assets/img/portfolio/portfolio-.jpg',
      name: 'Youthera',
      category : 'web app',
      url : '',
      tech : 'Html,Css,Js,Php,Ajax',
      desc : ' Youthera is an web application platform created for users to inteact at one place. It has features like posts,creating community, personal chats. The main feature of youthera is weekly group discussions.It gives all clients a platform to come together and share their thoughts and views.',
    },
    {
      id : 4,
      imgSrc: 'assets/img/portfolio/portfolio-4.png',
      name: 'Portfolio',
      category : 'website',
      url : '',
      tech : 'React.js , Bootstrap5',
      desc : ' This is my personal portfolio websites created in React.js. It has amazing scrolling features along with typewriter effect on homepage.',
    },
    {
      id : 5,
      imgSrc: 'assets/img/portfolio/portfolio-5.png',
      name: 'Blogs App',
      category : 'website',
      url : '',
      tech : 'React.js',
      desc : ' This is a simple react app showing bolgs. We can add a new blog or delete an existing blog. We can also view complete detail of the selected blog.',
    },
    
]